---
- name: Install yum dependency
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - python3
      - python3-pip
      - python3-devel
      - httpd
      - python3-mod_wsgi

- name: Update pip3
  shell: pip3 install -U pip

- name: Install keystone python package
  pip:
    name:
      - keystone==20.0.0
      - python-openstackclient==5.8.0
      - PyMySQL==1.0.2
    executable: pip3
    # extra_args: -i https://pypi.tuna.tsinghua.edu.cn/simple
    extra_args: -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com

- name: Create group "keystone"
  group:
    name: keystone
    state: present

- name: Add the user "keystone"
  user:
    name: keystone
    group: keystone

- name: Create keystone configuration directory
  file:
    path: /etc/keystone
    state: directory
    mode: "0755"

- name: Create keystone log directory
  file:
    path: /var/log/keystone
    state: directory
    mode: "0755"
    owner: keystone
    group: keystone
