---
- name: Template to /etc/keystone/keystone.conf
  template:
    src: keystone.conf.j2
    dest: /etc/keystone/keystone.conf
    owner: keystone
    group: keystone
    mode: "0644"

- name: Create httpd configuration file
  copy:
    src: keystone.conf
    dest: /etc/httpd/conf.d
    owner: root
    group: root
    mode: "0644"

- name: Template to /root/admin-openrc
  template:
    src: admin-openrc.j2
    dest: /root/admin-openrc
