---
- name: Template to /etc/keystone/keystone.conf
  template:
    src: keystone.conf.j2
    dest: /etc/keystone/keystone.conf
    owner: keystone
    group: keystone
    mode: "0644"

- name: Template to /etc/httpd/conf.d/keystone.conf
  template:
    src: wsgi-keystone.conf.j2
    dest: /etc/httpd/conf.d/keystone.conf
    owner: root
    group: root
    mode: "0644"

- name: Template to /root/openrc-admin
  template:
    src: openrc-admin.j2
    dest: /root/openrc-admin
