- name: install yum dependency
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - python3
      - python3-pip
      - python3-devel
      - httpd
      - mod_wsgi

- name: Update pip3
  shell: pip3 install -U pip

- name: Install keystone python package
  pip:
    name: keystone==20.0.0
    executable: pip3
    extra_args: -i https://pypi.tuna.tsinghua.edu.cn/simple
